### ISSUE TITLE
Se debería desdoblar en dos pruebas independientes

### ISSUE THREAD

**Issue by evolentini** [Martin-MT/TP3-TSSE#2]
Se debería desdoblar la prueba 

https://github.com/Martin-MT/TP3-TSSE/blob/f336846826faf2b1010786649f0ceb39d61652cb/leds/test/test_leds.c#L61-L70

como dos pruebas independientes, una donde se consulta por un led apagado y otra donde se consulta por un led encendido. Lo más razonable para preguntar por un led apagado justo después del inicio porque ya sabemos que todos quedan apagados. Para probar con un led encendido lo ideal es repetir la secuencia de esta prueba, que ya también sabemos que funciona.

https://github.com/Martin-MT/TP3-TSSE/blob/f336846826faf2b1010786649f0ceb39d61652cb/leds/test/test_leds.c#L28-L31

**Comment by Martin-MT** [comment]
Entiendo, había extendido la prueba de ver si un led estaba encendido a la situación de que diera verdadero estando prendido, y que diera falso estando apagado, pero no es necesario probar todas las combinaciones porque no está en la definición de lo que se busca hacer ahí.
Ya lo modifiqué
