### ISSUE TITLE
Se debe utilizar el assert mas descriptivo posible

### ISSUE THREAD

**Issue by evolentini** [Martin-MT/TP3-TSSE#3]
Se secuencia 

https://github.com/Martin-MT/TP3-TSSE/blob/f336846826faf2b1010786649f0ceb39d61652cb/leds/test/test_leds.c#L67-L69

Se puede reescribir como

```c
Led_TurnOff(LED);
TEST_ASSERT_TRUE(Led_IsOff(LED));
```

**Comment by Martin-MT** [comment]
Se realizan los cambios
